global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets: ['localhost:9090']

# Flask app metrics
- job_name: flask
  metrics_path: /metrics
  static_configs:
    - targets: ['backend:8000']

# MySQL exporter metrics
- job_name: mysql
  static_configs:
    - targets: ['mysqld-exporter:9104']

# NGINX exporter metrics
- job_name: nginx
  static_configs:
    - targets: ['nginx-exporter:9113']

