services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - backnet
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    networks:
      - backnet
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
  mysqld-exporter:
    image: prom/mysqld-exporter:v0.15.1
    env:
      DATA_SOURCE_NAME: exporter:exporterpass@tcp(db:3306)/
    networks:
      - backnet
    restart: unless-stopped
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    command: ["-nginx.scrape-uri=http://proxy:8080/nginx_status"]
    networks:
      - frontnet
      - backnet
    restart: unless-stopped
volumes:
  prom_data:
networks:
  backnet:
    external: true
    name: nginx-flask-mysql_backnet
  frontnet:
    external: true
    name: nginx-flask-mysql_frontnet

